name: Deploy

# disabled as site now deployed through netlify
# on:
#   push:
#     branches:
#       - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - name: Build
      run: |
        yarn install
        yarn run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
